### PR TITLE
Ansible v2.1

### PR DESCRIPTION
**Pull request by austinhyde**
WIP PR for 2.1 compatibility.

Supercedes and includes #7

### CODE REVIEW

**Comment by austinhyde** [comment]
This should work at this point for 2.0 work, pending the merge of [ansible/ansible #14218](https://github.com/ansible/ansible/pull/14218).

2.1 (currently the develop branch) appears to have changed some of the command invocation conventions, which breaks things.

**Comment by dch** [comment]
this is awesome -- thanks so much for publishing it. Would you be interested in having this merged to ansible core?

**Comment by Infiniverse** [comment]
@dch I was wondering whether it might be better to augment the existing jail/iocage connector so that they can connect over ssh if required.

**Comment by austinhyde** [comment]
@dch I'm not sure it's worth merging in its current form, as it uses some rather hacky workarounds for internal API weirdness. I'm not opposed to the idea in general, but I currently can't commit much time to maintain it.

@Infiniverse FWIW, the current implementation is basically a re-implementation of the built-in jail connector run over the SSH connector. It's been a while since I've messed with this, but IIRC there's some issues with using the actual jail connector over ssh. I'll revisit it as a cleaner implementation though.

@BigJ64 I think you're using this branch, is this stable at this point that we can merge to master? I don't see any reason to continue supporting 2.0.

**Comment by Infiniverse** [comment]
@austinhyde I'm actually using the iocage connector, which is _also_ a wrapper around the jail connector. :) It would be nice to find a way to make them all sing together.

**Comment by BigJ64** [comment]
@austinhyde I think this has been plenty stable enough to become the new master.  Only suggestion might to branch the old 1.9 version from master and make it available if people need it but I could see that not being necessary at all.

**Comment by austinhyde** [comment]
I split the old 1.9 compatible code off into `legacy-1.9`.

**Pull request merged**
