### PR TITLE
Switch to become plugins

### PR DESCRIPTION
**Pull request by kuPyxa**

### CODE REVIEW

**Comment by madpilot78** [comment]
I have tried using this patch, since I'm running into rpoblems with ansible 2.8, but it's not working for me.

I get this error:

```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/usr/local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 664, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/action/service.py", line 55, in run
    facts = self._execute_module(module_name='setup', module_args=dict(gather_subset='!all', filter='ansible_service_mgr'), task_vars=task_vars)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 836, in _execute_module
    self._transfer_data(remote_module_path, module_data)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 447, in _transfer_data
    self._transfer_file(afile, remote_path)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 424, in _transfer_file
    self._connection.put_file(local_path, remote_path)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/connection/sshjail.py", line 437, in put_file
    self._copy_file(tmp, out_path)
  File "/usr/local/lib/python3.6/site-packages/ansible/plugins/connection/sshjail.py", line 407, in _copy_file
    copycmd = plugin.build_become_command(' '.join(['cp', from_file, to_file]), shell)
AttributeError: 'NoneType' object has no attribute 'build_become_command'

jail@host | FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

**Comment by madpilot78** [comment]
I followup to myself, to state, I actually got that error because I forgot the "become" flag, so no become plugin was present, as the error states.

If I pass the "-b" flag(or have become: yes in the play) everything works.

Maybe adding a check for this condition could be useful.

**Comment by dch** [comment]
BTW this PR works brilliantly. @austinhyde if you're not actively using this we could move it to a "freebsd community" fork?

**Comment by austinhyde** [comment]
My apologies for the terribly long time without a response. 

It's true that I am no longer using this project, and no longer have any "real" machines to test against, which has made accepting PRs much more onerous than it used to be. Fortunately, I've recently had some time to set up Vagrant (now on master), which should allow much easier testing of PRs.

In this case, I was able to confirm that this PR
- does not break on Ansible 2.5
- on master, shows a deprecation warning on 2.9
- on this branch, shows no deprecation warning and works as expected on 2.9

---

This PR aside, in response to @dch - I would definitely be open to transferring this to someone else that's more actively using it or some sort of community organization. If no one is willing to take that on or has ideas on where this can live, I can continue to steward the project, and make some of you co-maintainers.

Thoughts?

**Comment by madpilot78** [comment]
I would not be able to be a maintainer for the project because I am not a python programmer, I know the language only superficially.

But I'd like to add it to the official FreeBSD ports tree.

It would be much easier if a new release was cut from it here on github to use as a basis.

**Pull request merged**
